CREATE DATABASE ab_testing_db;

-- 1. first 5 rows from the ab_test_data table.

SELECT * FROM ab_test_data 
LIMIT 5;

-- 2. count total number of rows in the table.

SELECT COUNT(*)
FROM ab_test_data;

-- 3. display unique experiment groups present in the table.

SELECT DISTINCT(`group`)
FROM ab_test_data;

-- 4. check whether duplicate user_ids still exist in SQL table

SELECT user_id, COUNT(*) AS duplicate_count
FROM ab_test_data
GROUP BY user_id
HAVING COUNT(*) > 1;

-- 5. count total users in each experiment group.

SELECT COUNT(user_id), (`group`)
FROM ab_test_data
GROUP BY (`group`);

-- 6. count converted users in each experiment group.

SELECT `group`,COUNT(user_id)
FROM ab_test_data 
WHERE converted = 1
GROUP BY `group`;

-- 7. calculate conversion rate for each experiment group directly in SQL

SELECT 
      `group`,
      AVG(converted) AS conversion_rate
FROM ab_test_data
GROUP BY `group`;      

-- 8. calculate relative conversion lift/drop of the treatment group compared to the control group

SELECT 
(
    (
        AVG(CASE 
                WHEN `group` = 'treatment' 
                THEN converted 
            END)
        -
        AVG(CASE 
                WHEN `group` = 'control' 
                THEN converted 
            END)
    )
    /
    AVG(CASE 
            WHEN `group` = 'control' 
            THEN converted 
        END)
) * 100 AS relative_conversion_lift
FROM ab_test_data;

-- 9. calculate weekly conversion trends for each experiment group

SELECT 
      `group`,
      AVG(converted) AS conversion_rate,
      `week`
FROM ab_test_data
GROUP BY `group`,`week`;

-- 10. count total users per week for each experiment group.

SELECT COUNT(user_id),`group`,`week`
FROM ab_test_data
GROUP BY `group`,`week`;

-- 11. compare weekly conversion rates between control and treatment side-by-side.

SELECT 
    `week`,
    AVG(
        CASE 
            WHEN `group` = 'control' 
            THEN converted 
        END
    ) AS control_rate,
    AVG(
        CASE 
            WHEN `group` = 'treatment' 
            THEN converted 
        END
    ) AS treatment_rate
FROM ab_test_data
GROUP BY `week`
ORDER BY `week`;

-- 12. estimate monthly conversions for control and treatment groups.

SELECT 
      `group`,
      AVG(converted) * 1000000
      AS estimated_monthly_conversion
FROM ab_test_data
GROUP BY `group`;

-- 13. expected monthly revenue generated by each experiment group.

SELECT 
      `group`,
      AVG(converted) * 1000000 * 500
      AS  estimated_monthly_revenue
FROM ab_test_data
GROUP BY `group`;

-- 14. one summarized query containing the main experiment KPIs.

SELECT 

    COUNT(user_id) AS total_users,

    SUM(converted) AS total_conversions,

    AVG(converted) AS overall_conversion_rate,

    AVG(
        CASE 
            WHEN `group` = 'control'
            THEN converted
        END
    ) AS control_conversion_rate,

    AVG(
        CASE 
            WHEN `group` = 'treatment'
            THEN converted
        END
    ) AS treatment_conversion_rate,

    (
        (
            AVG(
                CASE 
                    WHEN `group` = 'treatment'
                    THEN converted
                END
            )
            -
            AVG(
                CASE 
                    WHEN `group` = 'control'
                    THEN converted
                END
            )
        )
        /
        AVG(
            CASE 
                WHEN `group` = 'control'
                THEN converted
            END
        )
    ) * 100 AS relative_conversion_lift

FROM ab_test_data;

-- 15. one clean dataset for Power BI visualizations.

SELECT 
	`week`,
	`group`,
	COUNT(user_id) AS total_users,
	SUM(converted) AS total_conversions,
	AVG(converted) AS conversion_rate
FROM ab_test_data
GROUP BY `week`, `group`
ORDER BY `week`, `group`;